name = "LogitNash"
uuid = "56ed5f9e-c32e-46b8-b489-5928d745fddb"
version = "0.2.3"
authors = ["votroto <tomas.votroubek@outlook.com>"]

[workspace]
projects = ["test"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1.12.0"
