name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'

      - uses: julia-actions/julia-buildpkg@v1

      - name: Run Tests and Generate Coverage
        run: |
          julia --project=. --color=yes -e 'using Pkg; Pkg.test(julia_args=["--code-coverage=coverage.info","--code-coverage=@src","--check-bounds=yes"])'

      - name: Update Coverage Badge Gist
        # Prevent PRs from polluting the coverage badge
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: "7cc2561e5897bc8c43270ce659b45199"
        run: |
          COVERAGE=$(awk '/^LF:/ { total += substr($0,4) } /^LH:/ { hit += substr($0,4) } END { if (total > 0) printf "%.2f", (hit / total) * 100; else print "0.00" }' coverage.info)
          COLOR=$(awk -v cov="$COVERAGE" 'BEGIN { if(cov == 100) print "brightgreen"; else if (cov >= 90) print "yellow"; else print "red" }')

          # shields.io json format
          cat << EOF > coverage.json
          {
            "schemaVersion": 1,
            "label": "Coverage",
            "message": "${COVERAGE} %",
            "color": "${COLOR}"
          }
          EOF

          echo "Coverage: $COVERAGE %"
          gh gist edit "$GIST_ID" --filename LogitNashCoverage.json coverage.json