name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: julia-actions/setup-julia@v3
        with:
          version: '1'

      - uses: julia-actions/julia-buildpkg@v1

      - name: Run Tests and Generate Coverage
        run: |
          julia --project=. --color=yes -e 'using Pkg; Pkg.test(julia_args=["--code-coverage=coverage.info","--code-coverage=@src","--check-bounds=yes"])'

      - name: Update Coverage Badge Gist
        # Prevent PRs from polluting the coverage badge
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: "7cc2561e5897bc8c43270ce659b45199"
        run: |
          COVERAGE=$(awk '/^LF:/ { total += substr($0,4) } /^LH:/ { hit += substr($0,4) } END { if (total > 0) printf "%.2f", (hit / total) * 100; else print "0.00" }' coverage.info)
          COLOR=$(awk -v cov="$COVERAGE" 'BEGIN { if(cov == 100) print "#4ADE80"; else if (cov >= 90) print "#FDE047"; else print "#F87171" }')

          cat << EOF > coverage.svg
          <svg xmlns="http://www.w3.org/2000/svg" width="120" height="20">
            <clipPath id="r">
              <rect width="120" height="20" rx="2"/>
            </clipPath>

            <g clip-path="url(#r)">
              <rect width="60" height="20" fill="#333"/>
              <rect x="60" width="60" height="20" fill="${COLOR}"/>
            </g>

            <g text-anchor="middle" font-family="monospace" font-size="10" dominant-baseline="central">
              <text x="30" y="10" fill="#fff">Coverage</text>
              <text x="90" y="10">${COVERAGE} %</text>
            </g>
          </svg>
          EOF

          echo "Coverage: $COVERAGE %"
          gh gist edit "$GIST_ID" --filename LogitNashCoverage.svg coverage.svg